image: java

stages:
  - build
  - test
  - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/src/.gradle
  - chmod +x `pwd`/src/gradlew
  - cd ./src/

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 week
  only:
    - master

java:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml

deploy:
  stage: deploy
  script:
    # - ./deploy
    - echo "Deploy Stage"

after_script:
  - echo "End CI"